updating the onboarding_to_cluster docs
operate-first/support pull request #550
Opened 2022-04-01 22:45 UTC by Gregory-Pereira

includes changes to available cluster list, updating documentation link to `prod/moc` cluster-scope overlay, and adding new input for link to the new project's documentation.

Addresses: https://github.com/operate-first/support/issues/547#issuecomment-1083408585 Task 1

2022-04-01 22:45 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **4n4nd** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @4n4nd` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fsupport).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/support/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["4n4nd"]} -->

2022-04-01 22:45 UTC, sesheta commented
@Gregory-Pereira: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | 1daffe9b864b187fcee5668846075c69f6c6f574 | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/operate-first_support/550/pre-commit/1510025605997924352) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=operate-first&repo=support&pr=550). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/operate-first/support/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-04-01 22:49 UTC, sesheta commented
@Gregory-Pereira: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | b395823091702fe1221fda8f86fdb7105203d127 | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/operate-first_support/550/pre-commit/1510026474638282752) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=operate-first&repo=support&pr=550). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/operate-first/support/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-04-04 13:28 UTC, HumairAK commented on .github/ISSUE_TEMPLATE/onboarding_to_cluster.yaml
> +              - OSC-CL1 (dev)
remove (dev) part

2022-04-04 13:29 UTC, HumairAK commented on .github/ISSUE_TEMPLATE/onboarding_to_cluster.yaml
> +              https://github.com/operate-first/apps/tree/master/cluster-scope/overlays/prod/moc#available-clusters
I don't think we need to add a link when there's a drop down that's rendered

2022-04-04 13:40 UTC, 4n4nd commented on .github/ISSUE_TEMPLATE/onboarding_to_cluster.yaml
> +              - OSC-CL1 (dev)
Let's remove Rick too?

2022-04-21 22:07 UTC, Gregory-Pereira commented
bump @HumairAK

2022-07-21 01:04 UTC, sesheta commented
Issues go stale after 90d of inactivity.
Mark the issue as fresh with `/remove-lifecycle stale`.
Stale issues rot after an additional 30d of inactivity and eventually close.

If this issue is safe to close now please do so with `/close`.

/lifecycle stale

2022-08-17 10:36 UTC, mimotej commented
/remove-lifecycle stale

@Gregory-Pereira is this still relevant?

2022-08-30 20:40 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **humairak** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @humairak` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fsupport).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/support/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["humairak"]} -->

2022-08-30 20:41 UTC, Gregory-Pereira commented
yes it is, reping @HumairAK

2022-09-28 14:33 UTC, schwesig approved these changes
/lgtm
/approved

2022-09-28 14:33 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/support/pull/550#pullrequestreview-1123814308" title="LGTM">schwesig</a>*
**Once this PR has been reviewed and has the lgtm label**, please assign humairak for approval by writing `/assign @humairak` in a comment. For more information see:[The Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fsupport).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/support/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["humairak"]} -->

2022-09-28 14:35 UTC, schwesig commented
/assign @HumairAK

2022-10-04 07:09 UTC, durandom requested changes

2022-10-04 07:09 UTC, durandom commented on .github/ISSUE_TEMPLATE/4_onboarding_to_cluster.yaml
> +              - Morty
@Gregory-Pereira could you please update the list of clusters?

2022-10-04 07:09 UTC, durandom commented on .github/ISSUE_TEMPLATE/4_onboarding_to_cluster.yaml
> +              If you have any available documentation on your product, please provide the link here.
s/product/project/

2022-10-04 07:10 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/support/pull/550#pullrequestreview-1123814308" title="LGTM">schwesig</a>*
**Once this PR has been reviewed and has the lgtm label**, please ask for approval from humairak by writing `/assign @humairak` in a comment. For more information see:[The Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fsupport).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/support/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["humairak"]} -->

2023-01-02 08:28 UTC, sesheta commented
Issues go stale after 90d of inactivity.
Mark the issue as fresh with `/remove-lifecycle stale`.
Stale issues rot after an additional 30d of inactivity and eventually close.

If this issue is safe to close now please do so with `/close`.

/lifecycle stale

2023-02-01 09:16 UTC, sesheta commented
Stale issues rot after 30d of inactivity.
Mark the issue as fresh with `/remove-lifecycle rotten`.
Rotten issues close after an additional 30d of inactivity.

If this issue is safe to close now please do so with `/close`.

/lifecycle rotten

2023-03-03 09:20 UTC, sesheta commented
Rotten issues close after 30d of inactivity.
Reopen the issue with `/reopen`.
Mark the issue as fresh with `/remove-lifecycle rotten`.

/close

2023-03-03 09:20 UTC, closed without merging

2023-03-03 09:20 UTC, sesheta commented
@sesheta: Closed this PR.

<details>

In response to [this](https://github.com/operate-first/support/pull/550#issuecomment-1453219167):

>Rotten issues close after 30d of inactivity.
>Reopen the issue with `/reopen`.
>Mark the issue as fresh with `/remove-lifecycle rotten`.
>
>/close


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>